<?php


namespace App\Db;


class MySQLO extends AbstractMySQL
{

    public function update(ITableRow $row)
    {
//        parent::update($table_name, $values, $where); // TODO: Change the autogenerated stub
    }

}